export const GETARTICLELIST = 'home/getArticleList'
export const GETRANKLIST = 'home/getRankList'
export const CHANGEPAGE = 'home/changePage'
export const PREVPAGE = 'home/prevPage'
export const NEXTPAGE = 'home/nextPage'