export const GETARTICLEMSG = 'article/getArticleMsg'
export const GETARTICLECONTENT = 'article/getArticleContent'
export const GETUSERINFO = 'article/getUserInfo'
export const GETCOMMENTLIST = 'article/getCommentList'
export const COMMENTTEXTCHANGE = 'article/commentTextChange'
export const COMMENTSEND = 'article/commentSend'